=== gyorilab/mira/mira/resources/amr_schemas/petrinet/petrinet_v0.6.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "header": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "schema": {
          "type": "string",
          "format": "uri"
        },
        "schema_name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "model_version": {
          "type": "string"
        }
      },
      "required": ["name", "schema", "description"]
    },
    "properties": {
      "type": "object"
    },
    "model": {
      "type": "object",
      "properties": {
        "states": {
          "$ref": "#/$defs/states"
        },
        "transitions": {
          "$ref": "#/$defs/transitions"
        }
      },
      "additionalProperties": false,
      "required": ["states", "transitions"]
    },
    "semantics": {
      "type": "object",
      "description": "Information specific to a given semantics (e.g., ODEs) associated with a model.",
      "properties": {
        "ode": {
          "$ref": "#/$defs/odeSemantics"
        },
        "typing": {
          "description": "(Optional) Information for aligning models for stratification",
          "$ref": "#/$defs/typingSemantics"
        },
        "span": {
          "type": "array",
          "description": "(Optional) Legs of a span, each of which are a full ASKEM Petri Net",
          "items": {
            "type": "object",
            "$ref": "#/$defs/typingSemantics"
          }
        }
      }
    },
    "metadata": {
      "type": "object",
      "description": "(Optional) Information not useful for execution of the model, but that may be useful to some consumer in the future. E.g. creation timestamp or source paper's author."
    }
  },
  "$defs": {
    "states": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "grounding": {
            "$ref": "#/$defs/grounding"
          },
          "units": {
            "$ref": "#/$defs/unit"
          }
        },
        "required": ["id"]
      }
    },
    "transitions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "input": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "output": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "grounding": {
            "$ref": "#/$defs/grounding"
          },
          "properties": {
            "$ref": "#/$defs/properties"
          }
        },
        "required": ["id", "input", "output"]
      }
    },
    "observables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "grounding": {
            "$ref": "#/$defs/grounding"
          },
          "states": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "expression": {
            "type": "string"
          },
          "expression_mathml": {
            "type": "string"
          }
        },
        "required": ["id"]
      }
    },
    "properties": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "grounding": {
          "$ref": "#/$defs/grounding"
        }
      },
      "required": ["name"],
      "additionalProperties": true
    },
    "distribution": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "parameters": {
          "type": "object"
        }
      },
      "required": ["type", "parameters"],
      "additionalProperties": true
    },
    "unit": {
      "type": "object",
      "properties": {
        "expression": {
          "type": "string"
        },
        "expression_mathml": {
          "type": "string"
        }
      },
      "additionalProperties": true
    },
    "grounding": {
      "type": "object",
      "properties": {
        "identifiers": {
          "type": "object"
        },
        "modifiers": {
          "type": "object"
        }
      },
      "required": ["identifiers"],
      "additionalProperties": false
    },
    "provenance": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "value"],
      "additionalProperties": false
    },
    "metadatum": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "value"],
      "additionalProperties": false
    },
    "dataset": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "column": {
          "type": "string"
        },
        "metadata": {
          "type": "object"
        }
      },
      "required": ["id"],
      "additionalProperties": false
    },
    "paper": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "doi": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "equations": {
          "type": "array",
          "items": {
            "type": "object"
          }
        },
        "metadata": {
          "type": "object"
        }
      },
      "required": ["id", "doi"],
      "additionalProperties": false
    },
    "typingSemantics": {
      "type": "object",
      "properties": {
        "system": {
          "type": "object",
          "description": "A Petri net representing the 'type system' that is necessary to align states and transitions across different models during stratification.",
          "$ref": "#"
        },
        "map": {
          "type": "array",
          "description": "A map between the (state and transition) nodes of the model and the (state and transition) nodes of the type system",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "required": ["system", "map"]
    },
    "odeSemantics": {
      "type": "object",
      "properties": {
        "rates": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "target": {
                "type": "string"
              },
              "expression": {
                "type": "string"
              },
              "expression_mathml": {
                "type": "string"
              }
            }
          }
        },
        "initials": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "target": {
                "type": "string"
              },
              "expression": {
                "type": "string"
              },
              "expression_mathml": {
                "type": "string"
              }
            }
          }
        },
        "parameters": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "value": {
                "type": "number"
              },
              "grounding": {
                "$ref": "#/$defs/grounding"
              },
              "distribution": {
                "$ref": "#/$defs/distribution"
              },
              "units": {
                "$ref": "#/$defs/unit"
              }
            },
            "required": ["id"]
          }
        },
        "time": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "units": {
              "$ref": "#/$defs/unit"
            }
          },
          "required": ["id"]
        }
      },
      "required": []
    }
  },
  "additionalProperties": true,
  "required": ["header", "model"]
}

=== gyorilab/mira/notebooks/hackathon_2024.02/scenario6/scenario6_chen_petrinet.json
{
 "header": {
  "name": "Model",
  "schema": "https://raw.githubusercontent.com/DARPA-ASKEM/Model-Representations/petrinet_v0.6/petrinet/petrinet_schema.json",
  "schema_name": "petrinet",
  "description": "Model",
  "model_version": "0.1"
 },
 "properties": {},
 "model": {
  "states": [
   {
    "id": "r_1",
    "name": "r_1",
    "grounding": {
     "identifiers": {},
     "modifiers": {
      "species": "1"
     }
    }
   },
   {
    "id": "r_2",
    "name": "r_2",
    "grounding": {
     "identifiers": {},
     "modifiers": {
      "species": "2"
     }
    }
   },
   {
    "id": "r_3",
    "name": "r_3",
    "grounding": {
     "identifiers": {},
     "modifiers": {
      "species": "3"
     }
    }
   },
   {
    "id": "p_1",
    "name": "p_1",
    "grounding": {
     "identifiers": {},
     "modifiers": {
      "species": "1"
     }
    }
   },
   {
    "id": "p_2",
    "name": "p_2",
    "grounding": {
     "identifiers": {},
     "modifiers": {
      "species": "2"
     }
    }
   },
   {
    "id": "p_3",
    "name": "p_3",
    "grounding": {
     "identifiers": {},
     "modifiers": {
      "species": "3"
     }
    }
   }
  ],
  "transitions": [
   {
    "id": "t1",
    "input": [
     "r_1"
    ],
    "output": [],
    "properties": {
     "name": "t1"
    }
   },
   {
    "id": "t2",
    "input": [
     "r_2"
    ],
    "output": [],
    "properties": {
     "name": "t2"
    }
   },
   {
    "id": "t3",
    "input": [
     "r_3"
    ],
    "output": [],
    "properties": {
     "name": "t3"
    }
   },
   {
    "id": "t4",
    "input": [
     "r_1"
    ],
    "output": [
     "r_1",
     "p_1"
    ],
    "properties": {
     "name": "t4"
    }
   },
   {
    "id": "t5",
    "input": [
     "r_2"
    ],
    "output": [
     "r_2",
     "p_2"
    ],
    "properties": {
     "name": "t5"
    }
   },
   {
    "id": "t6",
    "input": [
     "r_3"
    ],
    "output": [
     "r_3",
     "p_3"
    ],
    "properties": {
     "name": "t6"
    }
   },
   {
    "id": "t7",
    "input": [
     "p_1"
    ],
    "output": [],
    "properties": {
     "name": "t7"
    }
   },
   {
    "id": "t8",
    "input": [
     "p_2"
    ],
    "output": [],
    "properties": {
     "name": "t8"
    }
   },
   {
    "id": "t9",
    "input": [
     "p_3"
    ],
    "output": [],
    "properties": {
     "name": "t9"
    }
   },
   {
    "id": "t10",
    "input": [
     "p_1"
    ],
    "output": [
     "p_1",
     "r_1"
    ],
    "properties": {
     "name": "t10"
    }
   },
   {
    "id": "t11",
    "input": [
     "p_1"
    ],
    "output": [
     "p_1",
     "r_2"
    ],
    "properties": {
     "name": "t11"
    }
   },
   {
    "id": "t12",
    "input": [
     "p_1"
    ],
    "output": [
     "p_1",
     "r_3"
    ],
    "properties": {
     "name": "t12"
    }
   }
  ]
 },
 "semantics": {
  "ode": {
   "rates": [
    {
     "target": "t1",
     "expression": "V_0*r_1",
     "expression_mathml": "<apply><times/><ci>V_0</ci><ci>r_1</ci></apply>"
    },
    {
     "target": "t2",
     "expression": "V_1*r_2",
     "expression_mathml": "<apply><times/><ci>V_1</ci><ci>r_2</ci></apply>"
    },
    {
     "target": "t3",
     "expression": "V_2*r_3",
     "expression_mathml": "<apply><times/><ci>V_2</ci><ci>r_3</ci></apply>"
    },
    {
     "target": "t4",
     "expression": "L_0*r_1",
     "expression_mathml": "<apply><times/><ci>L_0</ci><ci>r_1</ci></apply>"
    },
    {
     "target": "t5",
     "expression": "L_1*r_2",
     "expression_mathml": "<apply><times/><ci>L_1</ci><ci>r_2</ci></apply>"
    },
    {
     "target": "t6",
     "expression": "L_2*r_3",
     "expression_mathml": "<apply><times/><ci>L_2</ci><ci>r_3</ci></apply>"
    },
    {
     "target": "t7",
     "expression": "U_0*p_1",
     "expression_mathml": "<apply><times/><ci>U_0</ci><ci>p_1</ci></apply>"
    },
    {
     "target": "t8",
     "expression": "U_1*p_2",
     "expression_mathml": "<apply><times/><ci>U_1</ci><ci>p_2</ci></apply>"
    },
    {
     "target": "t9",
     "expression": "U_2*p_3",
     "expression_mathml": "<apply><times/><ci>U_2</ci><ci>p_3</ci></apply>"
    },
    {
     "target": "t10",
     "expression": "C_0*p_1",
     "expression_mathml": "<apply><times/><ci>C_0</ci><ci>p_1</ci></apply>"
    },
    {
     "target": "t11",
     "expression": "C_1*p_1",
     "expression_mathml": "<apply><times/><ci>C_1</ci><ci>p_1</ci></apply>"
    },
    {
     "target": "t12",
     "expression": "C_2*p_1",
     "expression_mathml": "<apply><times/><ci>C_2</ci><ci>p_1</ci></apply>"
    }
   ],
   "initials": [
    {
     "target": "r_1",
     "expression": "3.0",
     "expression_mathml": "<cn>3.0</cn>"
    },
    {
     "target": "r_2",
     "expression": "6.0",
     "expression_mathml": "<cn>6.0</cn>"
    },
    {
     "target": "r_3",
     "expression": "5.0",
     "expression_mathml": "<cn>5.0</cn>"
    },
    {
     "target": "p_1",
     "expression": "100.0",
     "expression_mathml": "<cn>100.0</cn>"
    },
    {
     "target": "p_2",
     "expression": "500.0",
     "expression_mathml": "<cn>500.0</cn>"
    },
    {
     "target": "p_3",
     "expression": "1.0",
     "expression_mathml": "<cn>1.0</cn>"
    }
   ],
   "parameters": [
    {
     "id": "V_0",
     "value": 0.3
    },
    {
     "id": "V_1",
     "value": 0.3
    },
    {
     "id": "V_2",
     "value": 0.3
    },
    {
     "id": "L_0",
     "value": 2.0
    },
    {
     "id": "L_1",
     "value": 2.0
    },
    {
     "id": "L_2",
     "value": 2.0
    },
    {
     "id": "U_0",
     "value": 0.15
    },
    {
     "id": "U_1",
     "value": 0.15
    },
    {
     "id": "U_2",
     "value": 0.015
    },
    {
     "id": "C_0",
     "value": 0.03
    },
    {
     "id": "C_1",
     "value": 0.03
    },
    {
     "id": "C_2",
     "value": 0.024
    }
   ],
   "observables": [],
   "time": {
    "id": "t"
   }
  }
 },
 "metadata": {
  "annotations": {}
 }
}

=== gyorilab/mira/notebooks/hackathon_2024.02/scenario6/scenario6_hunt_petrinet.json
{
 "header": {
  "name": "Model",
  "schema": "https://raw.githubusercontent.com/DARPA-ASKEM/Model-Representations/petrinet_v0.6/petrinet/petrinet_schema.json",
  "schema_name": "petrinet",
  "description": "Model",
  "model_version": "0.1"
 },
 "properties": {},
 "model": {
  "states": [
   {
    "id": "p_1",
    "name": "p_1",
    "grounding": {
     "identifiers": {},
     "modifiers": {}
    }
   },
   {
    "id": "r_1",
    "name": "r_1",
    "grounding": {
     "identifiers": {},
     "modifiers": {}
    }
   },
   {
    "id": "p_2",
    "name": "p_2",
    "grounding": {
     "identifiers": {},
     "modifiers": {}
    }
   },
   {
    "id": "r_2",
    "name": "r_2",
    "grounding": {
     "identifiers": {},
     "modifiers": {}
    }
   },
   {
    "id": "p_3",
    "name": "p_3",
    "grounding": {
     "identifiers": {},
     "modifiers": {}
    }
   },
   {
    "id": "r_3",
    "name": "r_3",
    "grounding": {
     "identifiers": {},
     "modifiers": {}
    }
   }
  ],
  "transitions": [
   {
    "id": "t1",
    "input": [
     "p_1",
     "p_1"
    ],
    "output": [
     "p_1",
     "p_1",
     "r_1"
    ],
    "properties": {
     "name": "t1"
    }
   },
   {
    "id": "t2",
    "input": [
     "p_1",
     "r_1"
    ],
    "output": [
     "p_1"
    ],
    "properties": {
     "name": "t2"
    }
   },
   {
    "id": "t3",
    "input": [
     "p_1",
     "r_1"
    ],
    "output": [
     "p_1",
     "r_1",
     "p_1"
    ],
    "properties": {
     "name": "t3"
    }
   },
   {
    "id": "t4",
    "input": [
     "p_1"
    ],
    "output": [],
    "properties": {
     "name": "t4"
    }
   },
   {
    "id": "t5",
    "input": [
     "p_1",
     "p_2"
    ],
    "output": [
     "p_1",
     "p_2",
     "r_2"
    ],
    "properties": {
     "name": "t5"
    }
   },
   {
    "id": "t6",
    "input": [
     "p_2",
     "r_2"
    ],
    "output": [
     "p_2"
    ],
    "properties": {
     "name": "t6"
    }
   },
   {
    "id": "t7",
    "input": [
     "p_2",
     "r_2"
    ],
    "output": [
     "p_2",
     "r_2",
     "p_2"
    ],
    "properties": {
     "name": "t7"
    }
   },
   {
    "id": "t8",
    "input": [
     "p_2"
    ],
    "output": [],
    "properties": {
     "name": "t8"
    }
   },
   {
    "id": "t9",
    "input": [
     "p_1",
     "p_3"
    ],
    "output": [
     "p_1",
     "p_3",
     "r_3"
    ],
    "properties": {
     "name": "t9"
    }
   },
   {
    "id": "t10",
    "input": [
     "p_3",
     "r_3"
    ],
    "output": [
     "p_3"
    ],
    "properties": {
     "name": "t10"
    }
   },
   {
    "id": "t11",
    "input": [
     "p_3",
     "r_3"
    ],
    "output": [
     "p_3",
     "r_3",
     "p_3"
    ],
    "properties": {
     "name": "t11"
    }
   },
   {
    "id": "t12",
    "input": [
     "p_3"
    ],
    "output": [],
    "properties": {
     "name": "t12"
    }
   }
  ]
 },
 "semantics": {
  "ode": {
   "rates": [
    {
     "target": "t1",
     "expression": "C_0*p_1/(1 + p_1**2/a_0**2)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>C_0</ci><ci>p_1</ci></apply><apply><plus/><cn>1</cn><apply><divide/><apply><power/><ci>p_1</ci><cn>2</cn></apply><apply><power/><ci>a_0</ci><cn>2</cn></apply></apply></apply></apply>"
    },
    {
     "target": "t2",
     "expression": "V_0*r_1/(1 + p_1**2/b_0**2)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>V_0</ci><ci>r_1</ci></apply><apply><plus/><cn>1</cn><apply><divide/><apply><power/><ci>p_1</ci><cn>2</cn></apply><apply><power/><ci>b_0</ci><cn>2</cn></apply></apply></apply></apply>"
    },
    {
     "target": "t3",
     "expression": "L_0*r_1/(1 + p_1/d_0)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>L_0</ci><ci>r_1</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_1</ci><ci>d_0</ci></apply></apply></apply>"
    },
    {
     "target": "t4",
     "expression": "U_0*p_1",
     "expression_mathml": "<apply><times/><ci>U_0</ci><ci>p_1</ci></apply>"
    },
    {
     "target": "t5",
     "expression": "C_1*p_1/(1 + p_2/a_1)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>C_1</ci><ci>p_1</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_2</ci><ci>a_1</ci></apply></apply></apply>"
    },
    {
     "target": "t6",
     "expression": "V_1*r_2/(1 + p_2/b_1)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>V_1</ci><ci>r_2</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_2</ci><ci>b_1</ci></apply></apply></apply>"
    },
    {
     "target": "t7",
     "expression": "L_1*r_2/(1 + p_2/d_1)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>L_1</ci><ci>r_2</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_2</ci><ci>d_1</ci></apply></apply></apply>"
    },
    {
     "target": "t8",
     "expression": "U_1*p_2",
     "expression_mathml": "<apply><times/><ci>U_1</ci><ci>p_2</ci></apply>"
    },
    {
     "target": "t9",
     "expression": "C_2*p_1/(1 + p_3/a_2)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>C_2</ci><ci>p_1</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_3</ci><ci>a_2</ci></apply></apply></apply>"
    },
    {
     "target": "t10",
     "expression": "V_2*r_3/(1 + p_3/b_2)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>V_2</ci><ci>r_3</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_3</ci><ci>b_2</ci></apply></apply></apply>"
    },
    {
     "target": "t11",
     "expression": "L_2*r_3/(1 + p_3/d_2)",
     "expression_mathml": "<apply><divide/><apply><times/><ci>L_2</ci><ci>r_3</ci></apply><apply><plus/><cn>1</cn><apply><divide/><ci>p_3</ci><ci>d_2</ci></apply></apply></apply>"
    },
    {
     "target": "t12",
     "expression": "U_2*p_3",
     "expression_mathml": "<apply><times/><ci>U_2</ci><ci>p_3</ci></apply>"
    }
   ],
   "initials": [
    {
     "target": "p_1",
     "expression": "100.0",
     "expression_mathml": "<cn>100.0</cn>"
    },
    {
     "target": "r_1",
     "expression": "3.0",
     "expression_mathml": "<cn>3.0</cn>"
    },
    {
     "target": "p_2",
     "expression": "500.0",
     "expression_mathml": "<cn>500.0</cn>"
    },
    {
     "target": "r_2",
     "expression": "6.0",
     "expression_mathml": "<cn>6.0</cn>"
    },
    {
     "target": "p_3",
     "expression": "1.0",
     "expression_mathml": "<cn>1.0</cn>"
    },
    {
     "target": "r_3",
     "expression": "5.0",
     "expression_mathml": "<cn>5.0</cn>"
    }
   ],
   "parameters": [
    {
     "id": "C_0",
     "value": 0.03
    },
    {
     "id": "a_0",
     "value": 60.0
    },
    {
     "id": "V_0",
     "value": 0.03
    },
    {
     "id": "b_0",
     "value": 120.0
    },
    {
     "id": "L_0",
     "value": 2.0
    },
    {
     "id": "d_0",
     "value": 120.0
    },
    {
     "id": "U_0",
     "value": 0.15
    },
    {
     "id": "C_1",
     "value": 0.03
    },
    {
     "id": "a_1",
     "value": 140.0
    },
    {
     "id": "V_1",
     "value": 0.03
    },
    {
     "id": "b_1",
     "value": 140.0
    },
    {
     "id": "L_1",
     "value": 2.0
    },
    {
     "id": "d_1",
     "value": 150.0
    },
    {
     "id": "U_1",
     "value": 0.15
    },
    {
     "id": "C_2",
     "value": 0.024
    },
    {
     "id": "a_2",
     "value": 170.0
    },
    {
     "id": "V_2",
     "value": 0.03
    },
    {
     "id": "b_2",
     "value": 180.0
    },
    {
     "id": "L_2",
     "value": 2.0
    },
    {
     "id": "d_2",
     "value": 260.0
    },
    {
     "id": "U_2",
     "value": 0.015
    }
   ],
   "observables": [],
   "time": {
    "id": "t"
   }
  }
 },
 "metadata": {
  "annotations": {}
 }
}

=== gyorilab/mira/notebooks/hackathon_2024.02/scenario1/scenario1_base_petrinet_amr.json
{
 "header": {
  "name": "EPI Scenario 1",
  "schema": "https://raw.githubusercontent.com/DARPA-ASKEM/Model-Representations/petrinet_v0.6/petrinet/petrinet_schema.json",
  "schema_name": "petrinet",
  "description": "EPI Scenario 1",
  "model_version": "0.1"
 },
 "properties": {},
 "model": {
  "states": [
   {
    "id": "S",
    "name": "S",
    "grounding": {
     "identifiers": {
      "ido": "0000514"
     },
     "modifiers": {}
    },
    "units": {
     "expression": "person",
     "expression_mathml": "<ci>person</ci>"
    }
   },
   {
    "id": "I_mild",
    "name": "I_mild",
    "grounding": {
     "identifiers": {
      "ido": "0000511"
     },
     "modifiers": {
      "status": "mild"
     }
    },
    "units": {
     "expression": "person",
     "expression_mathml": "<ci>person</ci>"
    }
   },
   {
    "id": "E",
    "name": "E",
    "grounding": {
     "identifiers": {
      "apollosv": "00000154"
     },
     "modifiers": {}
    },
    "units": {
     "expression": "person",
     "expression_mathml": "<ci>person</ci>"
    }
   },
   {
    "id": "I_case",
    "name": "I_case",
    "grounding": {
     "identifiers": {
      "ido": "0000511"
     },
     "modifiers": {
      "status": "case "
     }
    },
    "units": {
     "expression": "person",
     "expression_mathml": "<ci>person</ci>"
    }
   },
   {
    "id": "R",
    "name": "R",
    "grounding": {
     "identifiers": {
      "ido": "0000592"
     },
     "modifiers": {}
    },
    "units": {
     "expression": "person",
     "expression_mathml": "<ci>person</ci>"
    }
   },
   {
    "id": "D",
    "name": "D",
    "grounding": {
     "identifiers": {
      "ncit": "C28554"
     },
     "modifiers": {}
    },
    "units": {
     "expression": "person",
     "expression_mathml": "<ci>person</ci>"
    }
   }
  ],
  "transitions": [
   {
    "id": "t1",
    "input": [
     "I_mild",
     "S"
    ],
    "output": [
     "I_mild",
     "E"
    ],
    "properties": {
     "name": "t1"
    }
   },
   {
    "id": "t2",
    "input": [
     "I_case",
     "S"
    ],
    "output": [
     "I_case",
     "E"
    ],
    "properties": {
     "name": "t2"
    }
   },
   {
    "id": "t3",
    "input": [
     "E"
    ],
    "output": [
     "I_mild"
    ],
    "properties": {
     "name": "t3"
    }
   },
   {
    "id": "t4",
    "input": [
     "I_mild"
    ],
    "output": [
     "R"
    ],
    "properties": {
     "name": "t4"
    }
   },
   {
    "id": "t5",
    "input": [
     "E"
    ],
    "output": [
     "I_case"
    ],
    "properties": {
     "name": "t5"
    }
   },
   {
    "id": "t6",
    "input": [
     "I_case"
    ],
    "output": [
     "R"
    ],
    "properties": {
     "name": "t6"
    }
   },
   {
    "id": "t7",
    "input": [
     "I_case"
    ],
    "output": [
     "D"
    ],
    "properties": {
     "name": "t7"
    }
   }
  ]
 },
 "semantics": {
  "ode": {
   "rates": [
    {
     "target": "t1",
     "expression": "I_mild*S*r_SE_mild/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>I_mild</ci><ci>S</ci><ci>r_SE_mild</ci></apply><ci>N</ci></apply>"
    },
    {
     "target": "t2",
     "expression": "I_case*S*r_SE_case/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>I_case</ci><ci>S</ci><ci>r_SE_case</ci></apply><ci>N</ci></apply>"
    },
    {
     "target": "t3",
     "expression": "E*r_EI_mild/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>E</ci><ci>r_EI_mild</ci></apply><ci>N</ci></apply>"
    },
    {
     "target": "t4",
     "expression": "I_mild*r_I_mildR/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>I_mild</ci><ci>r_I_mildR</ci></apply><ci>N</ci></apply>"
    },
    {
     "target": "t5",
     "expression": "E*r_EI_case/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>E</ci><ci>r_EI_case</ci></apply><ci>N</ci></apply>"
    },
    {
     "target": "t6",
     "expression": "I_case*r_I_caseR/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>I_case</ci><ci>r_I_caseR</ci></apply><ci>N</ci></apply>"
    },
    {
     "target": "t7",
     "expression": "I_case*r_I_caseD/N",
     "expression_mathml": "<apply><divide/><apply><times/><ci>I_case</ci><ci>r_I_caseD</ci></apply><ci>N</ci></apply>"
    }
   ],
   "initials": [],
   "parameters": [
    {
     "id": "N",
     "value": 100.0,
     "units": {
      "expression": "person",
      "expression_mathml": "<ci>person</ci>"
     }
    },
    {
     "id": "r_SE_mild",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    },
    {
     "id": "r_SE_case",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    },
    {
     "id": "r_EI_mild",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    },
    {
     "id": "r_I_mildR",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    },
    {
     "id": "r_EI_case",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    },
    {
     "id": "r_I_caseR",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    },
    {
     "id": "r_I_caseD",
     "units": {
      "expression": "1/day",
      "expression_mathml": "<apply><power/><ci>day</ci><cn>-1</cn></apply>"
     }
    }
   ],
   "observables": [],
   "time": {
    "id": "t",
    "units": {
     "expression": "day",
     "expression_mathml": "<ci>day</ci>"
    }
   }
  }
 },
 "metadata": {
  "annotations": {
   "license": null,
   "authors": [],
   "references": [],
   "time_scale": null,
   "time_start": null,
   "time_end": null,
   "locations": [],
   "pathogens": [],
   "diseases": [],
   "hosts": [],
   "model_types": []
  }
 }
}
